# Generated by Django 5.0.1 on 2024-01-16 19:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realtor', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('sale_type', models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent')], default='for_sale', max_length=10)),
                ('photo_main', models.ImageField(upload_to='listing_imgs/%Y/%m/%d')),
                ('photo_1', models.ImageField(blank=True, upload_to='listing_imgs/%Y/%m/%d')),
                ('photo_2', models.ImageField(blank=True, upload_to='listing_imgs/%Y/%m/%d')),
                ('photo_3', models.ImageField(blank=True, upload_to='listing_imgs/%Y/%m/%d')),
                ('is_published', models.BooleanField(default=True)),
                ('listing_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
